const DYES = [
  "white",
  "orange",
  "magenta",
  "light_blue",
  "yellow",
  "lime",
  "pink",
  "gray",
  "light_gray",
  "cyan",
  "purple",
  "blue",
  "brown",
  "green",
  "red",
  "black",
];

const WOODS = ["oak", "spruce", "birch", "jungle", "acacia", "dark_oak"];

type LegacyBlock = string | readonly string[] | ((data: number) => string);

const dyed = (suffix: string) => (data: number) =>
  `${DYES[data & 15]}_${suffix}`;
const wooden = (suffix: string, mask: number) => (data: number) =>
  `${WOODS[data & mask] ?? WOODS[0]}_${suffix}`;

const LEGACY_BLOCKS: Record<number, LegacyBlock> = {
  0: "air",
  1: [
    "stone",
    "granite",
    "polished_granite",
    "diorite",
    "polished_diorite",
    "andesite",
    "polished_andesite",
  ],
  2: "grass_block",
  3: ["dirt", "coarse_dirt", "podzol"],
  4: "cobblestone",
  5: wooden("planks", 7),
  6: wooden("sapling", 7),
  7: "bedrock",
  8: "water",
  9: "water",
  10: "lava",
  11: "lava",
  12: ["sand", "red_sand"],
  13: "gravel",
  14: "gold_ore",
  15: "iron_ore",
  16: "coal_ore",
  17: wooden("log", 3),
  18: wooden("leaves", 3),
  19: ["sponge", "wet_sponge"],
  20: "glass",
  21: "lapis_ore",
  22: "lapis_block",
  23: "dispenser",
  24: "sandstone",
  25: "note_block",
  26: "red_bed",
  27: "powered_rail",
  28: "detector_rail",
  29: "sticky_piston",
  30: "cobweb",
  31: ["dead_bush", "short_grass", "fern"],
  32: "dead_bush",
  33: "piston",
  34: "piston_head",
  35: dyed("wool"),
  36: "moving_piston",
  37: "dandelion",
  38: [
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
  ],
  39: "brown_mushroom",
  40: "red_mushroom",
  41: "gold_block",
  42: "iron_block",
  43: [
    "smooth_stone",
    "sandstone",
    "oak_planks",
    "cobblestone",
    "bricks",
    "stone_bricks",
    "nether_bricks",
    "quartz_block",
  ],
  44: [
    "smooth_stone_slab",
    "sandstone_slab",
    "oak_slab",
    "cobblestone_slab",
    "brick_slab",
    "stone_brick_slab",
    "nether_brick_slab",
    "quartz_slab",
  ],
  45: "bricks",
  46: "tnt",
  47: "bookshelf",
  48: "mossy_cobblestone",
  49: "obsidian",
  50: "torch",
  51: "fire",
  52: "spawner",
  53: "oak_stairs",
  54: "chest",
  55: "redstone_wire",
  56: "diamond_ore",
  57: "diamond_block",
  58: "crafting_table",
  59: "wheat",
  60: "farmland",
  61: "furnace",
  62: "furnace",
  63: "oak_sign",
  64: "oak_door",
  65: "ladder",
  66: "rail",
  67: "cobblestone_stairs",
  68: "oak_wall_sign",
  69: "lever",
  70: "stone_pressure_plate",
  71: "iron_door",
  72: "oak_pressure_plate",
  73: "redstone_ore",
  74: "redstone_ore",
  75: "redstone_torch",
  76: "redstone_torch",
  77: "stone_button",
  78: "snow",
  79: "ice",
  80: "snow_block",
  81: "cactus",
  82: "clay",
  83: "sugar_cane",
  84: "jukebox",
  85: "oak_fence",
  86: "pumpkin",
  87: "netherrack",
  88: "soul_sand",
  89: "glowstone",
  90: "nether_portal",
  91: "jack_o_lantern",
  92: "cake",
  93: "repeater",
  94: "repeater",
  95: dyed("stained_glass"),
  96: "oak_trapdoor",
  97: [
    "infested_stone",
    "infested_cobblestone",
    "infested_stone_bricks",
    "infested_mossy_stone_bricks",
    "infested_cracked_stone_bricks",
    "infested_chiseled_stone_bricks",
  ],
  98: [
    "stone_bricks",
    "mossy_stone_bricks",
    "cracked_stone_bricks",
    "chiseled_stone_bricks",
  ],
  99: (data) =>
    data === 10 || data === 15 ? "mushroom_stem" : "brown_mushroom_block",
  100: (data) =>
    data === 10 || data === 15 ? "mushroom_stem" : "red_mushroom_block",
  101: "iron_bars",
  102: "glass_pane",
  103: "melon",
  104: "pumpkin_stem",
  105: "melon_stem",
  106: "vine",
  107: "oak_fence_gate",
  108: "brick_stairs",
  109: "stone_brick_stairs",
  110: "mycelium",
  111: "lily_pad",
  112: "nether_bricks",
  113: "nether_brick_fence",
  114: "nether_brick_stairs",
  115: "nether_wart",
  116: "enchanting_table",
  117: "brewing_stand",
  118: "cauldron",
  119: "end_portal",
  120: "end_portal_frame",
  121: "end_stone",
  122: "dragon_egg",
  123: "redstone_lamp",
  124: "redstone_lamp",
  125: wooden("planks", 7),
  126: wooden("slab", 7),
  127: "cocoa",
  128: "sandstone_stairs",
  129: "emerald_ore",
  130: "ender_chest",
  131: "tripwire_hook",
  132: "tripwire",
  133: "emerald_block",
  134: "spruce_stairs",
  135: "birch_stairs",
  136: "jungle_stairs",
  137: "command_block",
  138: "beacon",
  139: ["cobblestone_wall", "mossy_cobblestone_wall"],
  140: "flower_pot",
  141: "carrots",
  142: "potatoes",
  143: "oak_button",
  144: "skeleton_skull",
  145: "anvil",
  146: "trapped_chest",
  147: "light_weighted_pressure_plate",
  148: "heavy_weighted_pressure_plate",
  149: "comparator",
  150: "comparator",
  151: "daylight_detector",
  152: "redstone_block",
  153: "nether_quartz_ore",
  154: "hopper",
  155: "quartz_block",
  156: "quartz_stairs",
  157: "activator_rail",
  158: "dropper",
  159: dyed("terracotta"),
  160: dyed("stained_glass_pane"),
  161: (data) => `${WOODS[4 + (data & 1)]}_leaves`,
  162: (data) => `${WOODS[4 + (data & 1)]}_log`,
  163: "acacia_stairs",
  164: "dark_oak_stairs",
  165: "slime_block",
  166: "barrier",
  167: "iron_trapdoor",
  168: ["prismarine", "prismarine_bricks", "dark_prismarine"],
  169: "sea_lantern",
  170: "hay_block",
  171: dyed("carpet"),
  172: "terracotta",
  173: "coal_block",
  174: "packed_ice",
  175: ["sunflower", "lilac", "tall_grass", "large_fern", "rose_bush", "peony"],
  176: "white_banner",
  177: "white_wall_banner",
  178: "daylight_detector",
  179: "red_sandstone",
  180: "red_sandstone_stairs",
  181: "red_sandstone",
  182: "red_sandstone_slab",
  183: "spruce_fence_gate",
  184: "birch_fence_gate",
  185: "jungle_fence_gate",
  186: "dark_oak_fence_gate",
  187: "acacia_fence_gate",
  188: "spruce_fence",
  189: "birch_fence",
  190: "jungle_fence",
  191: "dark_oak_fence",
  192: "acacia_fence",
  193: "spruce_door",
  194: "birch_door",
  195: "jungle_door",
  196: "acacia_door",
  197: "dark_oak_door",
  198: "end_rod",
  199: "chorus_plant",
  200: "chorus_flower",
  201: "purpur_block",
  202: "purpur_pillar",
  203: "purpur_stairs",
  204: "purpur_block",
  205: "purpur_slab",
  206: "end_stone_bricks",
  207: "beetroots",
  208: "dirt_path",
  209: "end_gateway",
  210: "repeating_command_block",
  211: "chain_command_block",
  212: "frosted_ice",
  213: "magma_block",
  214: "nether_wart_block",
  215: "red_nether_bricks",
  216: "bone_block",
  217: "structure_void",
  218: "observer",
  251: dyed("concrete"),
  252: dyed("concrete_powder"),
  255: "structure_block",
};

for (let index = 0; index < 16; index += 1) {
  LEGACY_BLOCKS[219 + index] = `${DYES[index]}_shulker_box`;
  LEGACY_BLOCKS[235 + index] = `${DYES[index]}_glazed_terracotta`;
}

export type LegacyBlockNames = ReadonlyMap<number, string>;

export function legacyBlockName(
  id: number,
  data: number,
  registry?: LegacyBlockNames | null,
): string {
  const entry = LEGACY_BLOCKS[id];

  if (entry === undefined) {
    return registry?.get(id) ?? `legacy:block_${id}`;
  }
  if (typeof entry === "string") return `minecraft:${entry}`;
  if (typeof entry === "function") return `minecraft:${entry(data)}`;
  return `minecraft:${entry[data & 15] ?? entry[data & 7] ?? entry[0]}`;
}

const LEGACY_BIOMES: Record<number, string> = {
  0: "ocean",
  1: "plains",
  2: "desert",
  3: "windswept_hills",
  4: "forest",
  5: "taiga",
  6: "swamp",
  7: "river",
  8: "nether_wastes",
  9: "the_end",
  10: "frozen_ocean",
  11: "frozen_river",
  12: "snowy_plains",
  13: "snowy_slopes",
  14: "mushroom_fields",
  15: "mushroom_fields",
  16: "beach",
  17: "desert",
  18: "forest",
  19: "taiga",
  20: "windswept_hills",
  21: "jungle",
  22: "jungle",
  23: "sparse_jungle",
  24: "deep_ocean",
  25: "stony_shore",
  26: "snowy_beach",
  27: "birch_forest",
  28: "birch_forest",
  29: "dark_forest",
  30: "snowy_taiga",
  31: "snowy_taiga",
  32: "old_growth_pine_taiga",
  33: "old_growth_pine_taiga",
  34: "windswept_forest",
  35: "savanna",
  36: "savanna_plateau",
  37: "badlands",
  38: "wooded_badlands",
  39: "badlands",
  40: "small_end_islands",
  41: "end_midlands",
  42: "end_highlands",
  43: "end_barrens",
  44: "warm_ocean",
  45: "lukewarm_ocean",
  46: "cold_ocean",
  47: "warm_ocean",
  48: "deep_lukewarm_ocean",
  49: "deep_cold_ocean",
  50: "deep_frozen_ocean",
  127: "the_void",
  129: "sunflower_plains",
  130: "desert",
  131: "windswept_gravelly_hills",
  132: "flower_forest",
  133: "taiga",
  134: "swamp",
  140: "ice_spikes",
  149: "jungle",
  151: "sparse_jungle",
  155: "old_growth_birch_forest",
  156: "old_growth_birch_forest",
  157: "dark_forest",
  158: "snowy_taiga",
  160: "old_growth_spruce_taiga",
  161: "old_growth_spruce_taiga",
  162: "windswept_gravelly_hills",
  163: "windswept_savanna",
  164: "windswept_savanna",
  165: "eroded_badlands",
  166: "wooded_badlands",
  167: "badlands",
  168: "bamboo_jungle",
  169: "bamboo_jungle",
  170: "soul_sand_valley",
  171: "crimson_forest",
  172: "warped_forest",
  173: "basalt_deltas",
  174: "dripstone_caves",
  175: "lush_caves",
};

export function legacyBiomeId(value: unknown): number | null {
  if (typeof value !== "number" || !Number.isInteger(value)) return null;
  return value < 0 ? value & 0xff : value;
}

export function legacyBiomeName(id: number): string | null {
  const name = LEGACY_BIOMES[id];
  return name ? `minecraft:${name}` : null;
}

export function byteArray(value: unknown): ArrayLike<number> | null {
  if (Array.isArray(value)) return value;
  if (ArrayBuffer.isView(value) && !(value instanceof DataView)) {
    return value as unknown as ArrayLike<number>;
  }
  return null;
}

export function nibble(array: ArrayLike<number>, index: number): number {
  const value = array[index >> 1] ?? 0;
  return (index & 1) === 0 ? value & 0x0f : (value >> 4) & 0x0f;
}
